export const SCENEORDERTYPE_UPDATE = "SCENEORDERTYPE_UPDATE"
export const SCENEORDERTYPESTATUS_CHANGE = 'SCENEORDERTYPESTATUS_CHANGE'
export const SCENEORDERTABSTATUS_CHANGE = 'SCENEORDERTABSTATUS_CHANGE'
export const SCENEORDERTYPESHOW_CHANGE = "SCENEORDERTYPESHOW_CHANGE"